import os
import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "traveloop_project.settings")
django.setup()

from travelapp.models import City

cities_data = [
    {"name": "Delhi", "state": "Delhi", "cost_index": "$$", "popularity": 9, "famous_for": "Red Fort, Qutub Minar, Street Food", "image_url": "https://images.unsplash.com/photo-1587474260584-136574528ed5?q=80&w=1000&auto=format&fit=crop", "activities_json": {"scenic_spots": [{"name": "Red Fort", "cost": "Free", "duration": "2-3 hours", "description": "Historic Mughal fort with stunning architecture and history"}, {"name": "Qutub Minar", "cost": "₹40", "duration": "1-2 hours", "description": "Tallest brick minaret in the world, UNESCO World Heritage site"}], "food_experiences": [{"name": "Street Food Tour", "cost": "₹500", "duration": "3 hours", "description": "Explore Chandni Chowk's famous street food like parathas and jalebis"}] }},
    {"name": "Mumbai", "state": "Maharashtra", "cost_index": "$$$", "popularity": 10, "famous_for": "Gateway of India, Bollywood, Marine Drive", "image_url": "https://images.unsplash.com/photo-1522204523234-8729aa6e3d5f?q=80&w=1000&auto=format&fit=crop", "activities_json": {"landmarks": [{"name": "Gateway of India", "cost": "Free", "duration": "1 hour", "description": "Iconic arch monument built during British Raj"}, {"name": "Marine Drive", "cost": "Free", "duration": "2 hours", "description": "Scenic 3.6 km long promenade along Arabian Sea"}], "entertainment": [{"name": "Bollywood Studio Tour", "cost": "₹1500", "duration": "4 hours", "description": "Visit film studios and learn about Indian cinema"}] }},
    {"name": "Jaipur", "state": "Rajasthan", "cost_index": "$$", "popularity": 8, "famous_for": "Hawa Mahal, Amber Fort, Palaces", "image_url": "https://images.unsplash.com/photo-1477587458883-47145ed94245?q=80&w=1000&auto=format&fit=crop", "activities_json": {"historical_sites": [{"name": "Amber Fort", "cost": "₹200", "duration": "3 hours", "description": "Magnificent hilltop fort with mirror work and palace complex"}, {"name": "Hawa Mahal", "cost": "₹50", "duration": "1 hour", "description": "Palace of Winds with 953 windows for royal ladies"}], "cultural_experiences": [{"name": "Rajasthani Cooking Class", "cost": "₹1200", "duration": "4 hours", "description": "Learn to cook traditional Rajasthani dishes"}] }},
    {"name": "Agra", "state": "Uttar Pradesh", "cost_index": "$", "popularity": 10, "famous_for": "Taj Mahal, Agra Fort, Mughlai Cuisine", "image_url": "https://images.unsplash.com/photo-1564507592333-c60657eea523?q=80&w=1000&auto=format&fit=crop", "activities_json": {"monuments": [{"name": "Taj Mahal", "cost": "₹1100", "duration": "2-3 hours", "description": "World-famous white marble mausoleum and UNESCO site"}, {"name": "Agra Fort", "cost": "₹35", "duration": "2 hours", "description": "Massive red sandstone fort with palaces and mosques"}], "culinary": [{"name": "Mughlai Food Tour", "cost": "₹800", "duration": "3 hours", "description": "Taste authentic Mughlai biryanis and kebabs"}] }},
    {"name": "Goa", "state": "Goa", "cost_index": "$$$", "popularity": 9, "famous_for": "Scuba Diving, Jet Skiing, Nightlife, Beaches", "image_url": "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=1000&auto=format&fit=crop", "activities_json": {"water_sports": [{"name": "Scuba Diving", "cost": "₹2500", "duration": "4 hours", "description": "Explore underwater coral reefs and marine life"}, {"name": "Jet Skiing", "cost": "₹1200", "duration": "30 minutes", "description": "Thrilling jet ski ride along Calangute Beach"}], "beach_activities": [{"name": "Beach Hopping", "cost": "Free", "duration": "Full day", "description": "Visit popular beaches like Anjuna, Baga, and Palolem"}, {"name": "Sunset Cruise", "cost": "₹1800", "duration": "2 hours", "description": "Romantic cruise with cocktails and live music"}] }},
    {"name": "Kochi", "state": "Kerala", "cost_index": "$$", "popularity": 7, "famous_for": "Backwaters, Fort Kochi, Kathakali", "image_url": "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?q=80&w=1000&auto=format&fit=crop", "activities_json": {"backwaters": [{"name": "Houseboat Cruise", "cost": "₹3500", "duration": "Overnight", "description": "Stay on traditional houseboats and explore backwater villages"}, {"name": "Kayaking Tour", "cost": "₹1500", "duration": "3 hours", "description": "Paddle through serene backwaters and mangrove forests"}], "cultural": [{"name": "Kathakali Performance", "cost": "₹800", "duration": "2 hours", "description": "Traditional dance-drama with elaborate makeup and costumes"}] }},
    {"name": "Varanasi", "state": "Uttar Pradesh", "cost_index": "$", "popularity": 8, "famous_for": "Ganges River, Ghats, Spiritual Temples", "image_url": "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?q=80&w=1000&auto=format&fit=crop", "activities_json": {"spiritual": [{"name": "Ganga Aarti Ceremony", "cost": "Free", "duration": "1 hour", "description": "Sacred fire ritual at Dashashwamedh Ghat at sunset"}, {"name": "Temple Visit", "cost": "₹100", "duration": "2 hours", "description": "Visit Kashi Vishwanath Temple and other ancient shrines"}], "cultural": [{"name": "Sari Weaving Workshop", "cost": "₹1200", "duration": "3 hours", "description": "Learn traditional Banarasi silk weaving techniques"}] }},
    {"name": "Udaipur", "state": "Rajasthan", "cost_index": "$$$", "popularity": 9, "famous_for": "Lake Palace, City Palace, Romantic Lakes", "image_url": "https://images.unsplash.com/photo-1615861413645-1b48b9415c10?q=80&w=1000&auto=format&fit=crop", "activities_json": {"palaces": [{"name": "Lake Palace", "cost": "₹5000", "duration": "2 hours", "description": "Luxury palace hotel on Lake Pichola, now a museum"}, {"name": "City Palace", "cost": "₹300", "duration": "2-3 hours", "description": "Largest royal residence in Rajasthan with museums"}], "romantic": [{"name": "Sunset Boat Ride", "cost": "₹1200", "duration": "1 hour", "description": "Romantic boat ride on Lake Pichola with views of palaces"}] }},
    {"name": "Bengaluru", "state": "Karnataka", "cost_index": "$$$", "popularity": 8, "famous_for": "Lalbagh, Tech Hub, Breweries, Cubbon Park", "image_url": "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?q=80&w=1000&auto=format&fit=crop", "activities_json": {"parks": [{"name": "Lalbagh Botanical Garden", "cost": "₹30", "duration": "2 hours", "description": "120-acre garden with rare plants and glasshouse"}, {"name": "Cubbon Park", "cost": "Free", "duration": "2 hours", "description": "Green lung of Bangalore with historic statues and trees"}], "tech_experience": [{"name": "Tech Park Tour", "cost": "₹1000", "duration": "3 hours", "description": "Visit tech campuses and innovation hubs"}] }},
    {"name": "Chennai", "state": "Tamil Nadu", "cost_index": "$$", "popularity": 7, "famous_for": "Marina Beach, Kapaleeshwarar Temple, Filter Coffee", "image_url": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?q=80&w=1000&auto=format&fit=crop", "activities_json": {"beaches": [{"name": "Marina Beach", "cost": "Free", "duration": "2 hours", "description": "Second longest urban beach in the world"}, {"name": "Elliot's Beach", "cost": "Free", "duration": "2 hours", "description": "Popular beach for surfing and sunset views"}], "cultural": [{"name": "Filter Coffee Experience", "cost": "₹200", "duration": "1 hour", "description": "Learn to make authentic South Indian filter coffee"}] }}
]

def seed():
    City.objects.all().delete() # Clear existing just in case
    for data in cities_data:
        City.objects.create(
            name=data['name'],
            state=data['state'],
            country='India',
            cost_index=data['cost_index'],
            popularity=data['popularity'],
            famous_for=data['famous_for'],
            image_url=data['image_url'],
            activities_json=data.get('activities_json', {})
        )
    print("Successfully seeded 10 Indian cities.")

if __name__ == "__main__":
    seed()
