# Generated by Django 6.0.3 on 2026-05-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='famous_for',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Couple', 'Couple'), ('Family', 'Family'), ('Friends', 'Friends')], default='Single', max_length=50),
        ),
    ]
