# Generated by Django 6.0.3 on 2026-05-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_city_famous_for_trip_budget_trip_trip_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='activities_json',
            field=models.JSONField(blank=True, default=dict, help_text='JSON structure of activities and attractions'),
        ),
        migrations.AddField(
            model_name='stop',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Estimated cost for this stop', max_digits=12),
        ),
        migrations.AddField(
            model_name='trip',
            name='duration_days',
            field=models.IntegerField(default=0, help_text='Number of days for this trip'),
        ),
    ]
