# Generated by Django 6.0.3 on 2026-05-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_city_activities_json_stop_estimated_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='famous_events',
            field=models.CharField(blank=True, help_text='e.g. Sunburn Festival', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='famous_rides',
            field=models.CharField(blank=True, help_text='e.g. Jet Skiing, Banana Boat', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='num_travelers',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
